# Generated by Django 5.0 on 2023-12-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resetpasswordtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': [('povoleni', 'Správce povolení'), ('kvalifikace', 'Správce kvalifikací'), ('opravneni', 'Správce oprávnění'), ('vybaveni', 'Správce vybavení'), ('skupiny', 'Správce skupin'), ('stranky', 'Správce textových stránek'), ('komercni_udalosti', 'Správce komerčních událostí'), ('kurzy', 'Správce kurzů'), ('prezentacni_udalosti', 'Správce prezentačních událostí'), ('udalosti_pro_deti', 'Správce událostí pro děti'), ('spolecenske_udalosti', 'Správce společenských událostí'), ('lezecke_treninky', 'Správce lezeckých tréninků'), ('plavecke_treninky', 'Správce plaveckých tréninků'), ('zdravoveda', 'Správce zdravovědy'), ('clenska_zakladna', 'Správce členské základny'), ('detska_clenska_zakladna', 'Správce dětské členské základny'), ('bazenova_clenska_zakladna', 'Správce bazénové dětské členské základny'), ('lezecka_clenska_zakladna', 'Správce lezecké dětské členské základny'), ('dospela_clenska_zakladna', 'Správce dospělé členské základny'), ('transakce', 'Správce transakcí')]},
        ),
    ]
