# Generated by Django 4.2.2 on 2023-07-13 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={"permissions": [("spravce_povoleni", "Správce povolení")]},
        ),
    ]
