# Generated by Django 5.0 on 2023-12-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_permission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': [('povoleni', 'Správce povolení'), ('kvalifikace', 'Správce kvalifikací'), ('opravneni', 'Správce oprávnění'), ('vybaveni', 'Správce vybavení'), ('skupiny', 'Správce skupin'), ('stranky', 'Správce textových stránek'), ('komercni', 'Správce komerčních událostí'), ('kurz', 'Správce kurzů'), ('prezentacni', 'Správce prezentačních událostí'), ('pro-deti', 'Správce událostí pro děti'), ('spolecenska', 'Správce společenských událostí'), ('lezecky', 'Správce lezeckých tréninků'), ('plavecky', 'Správce plaveckých tréninků'), ('zdravoveda', 'Správce zdravovědy'), ('clenska_zakladna', 'Správce členské základny'), ('detska_clenska_zakladna', 'Správce dětské členské základny'), ('bazenova_clenska_zakladna', 'Správce bazénové dětské členské základny'), ('lezecka_clenska_zakladna', 'Správce lezecké dětské členské základny'), ('dospela_clenska_zakladna', 'Správce dospělé členské základny'), ('transakce', 'Správce transakcí')]},
        ),
    ]
