# Generated by Django 4.2.3 on 2023-08-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="positions",
            field=models.ManyToManyField(
                related_name="event_position_assignment_set",
                through="events.EventPositionAssignment",
                to="positions.eventposition",
            ),
        ),
    ]
