# Generated by Django 4.2.2 on 2023-06-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="age_limit",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Minimální věk účastníků"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="capacity",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Maximální počet účastníků"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(verbose_name="Popis"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Název"),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_end",
            field=models.DateTimeField(null=True, verbose_name="Končí"),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_start",
            field=models.DateTimeField(null=True, verbose_name="Začíná"),
        ),
    ]
