# Generated by Django 4.2.3 on 2023-08-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("positions", "0001_initial"),
        ("transactions", "0001_initial"),
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participantenrollment",
            old_name="datetime",
            new_name="created_datetime",
        ),
        migrations.RemoveField(
            model_name="participantenrollment",
            name="person",
        ),
        migrations.AddField(
            model_name="event",
            name="participants_enroll_list",
            field=models.CharField(
                choices=[("nahradnik", "nahradník"), ("schvalen", "schválen")],
                default="nahradnik",
                max_length=10,
                verbose_name="Přidat nové účastníky jako",
            ),
        ),
        migrations.AddField(
            model_name="participantenrollment",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="groups.group",
                verbose_name="Skupina",
            ),
        ),
        migrations.AlterField(
            model_name="eventpositionassignment",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="positions.eventposition",
                verbose_name="Pozice",
            ),
        ),
        migrations.AlterField(
            model_name="participantenrollment",
            name="state",
            field=models.CharField(
                choices=[
                    ("schvalen", "schválen"),
                    ("nahradnik", "nahradník"),
                    ("odminut", "odmítnut"),
                ],
                max_length=10,
                verbose_name="Stav přihlášky",
            ),
        ),
    ]
