# Generated by Django 4.2.3 on 2023-08-18 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantenrollment",
            name="person",
        ),
    ]
