# Generated by Django 4.2.3 on 2023-08-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizeroccurrenceassignment",
            name="position",
        ),
        migrations.AddField(
            model_name="organizeroccurrenceassignment",
            name="position_assignment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.eventpositionassignment",
                verbose_name="Pozice události",
            ),
            preserve_default=False,
        ),
    ]
