# Generated by Django 4.2.3 on 2023-08-28 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizerassignment",
            name="position_assignment",
        ),
    ]
