# Generated by Django 4.2.3 on 2023-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="capacity",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Maximální počet účastníků"
            ),
        ),
    ]
