# Generated by Django 4.2.2 on 2023-07-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_age_limit_alter_event_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventposition",
            name="template",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="eventposition",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Jméno"),
        ),
    ]
