# Generated by Django 4.2.3 on 2023-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Popis"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Místo konání"
            ),
        ),
    ]
