# Generated by Django 4.2.3 on 2023-08-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_participantenrollment_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="event",
        ),
        migrations.RemoveField(
            model_name="participantenrollment",
            name="person",
        ),
        migrations.AlterField(
            model_name="event",
            name="allowed_person_types",
            field=models.ManyToManyField(
                related_name="event_person_type_constraint_set",
                to="events.eventpersontypeconstraint",
            ),
        ),
    ]
