# Generated by Django 4.2.3 on 2023-08-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
        (
            "events",
            "0003_rename_datetime_participantenrollment_created_datetime_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="participantenrollment",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.transaction",
            ),
        ),
    ]
