# Generated by Django 4.2.3 on 2023-08-19 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
        ("groups", "0001_initial"),
        ("events", "0003_remove_participantenrollment_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="groups.group",
                verbose_name="Skupina",
            ),
        ),
        migrations.AlterField(
            model_name="eventpositionassignment",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="positions.eventposition",
                verbose_name="Pozice",
            ),
        ),
    ]
