# Generated by Django 4.2.3 on 2023-08-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0003_rename_datetime_participantenrollment_created_datetime_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantenrollment",
            name="transaction",
        ),
        migrations.AlterField(
            model_name="participantenrollment",
            name="state",
            field=models.CharField(
                choices=[
                    ("schvalen", "schválen"),
                    ("nahradnik", "nahradník"),
                    ("odmitnut", "odmítnut"),
                ],
                max_length=10,
                verbose_name="Stav přihlášky",
            ),
        ),
    ]
