# Generated by Django 4.2.3 on 2023-08-23 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0003_rename_datetime_participantenrollment_created_datetime_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantenrollment",
            name="transaction",
        ),
    ]
