# Generated by Django 4.2.3 on 2023-08-24 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_remove_participantenrollment_transaction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="participants_enroll_list",
            new_name="participants_enroll_state",
        ),
    ]
