# Generated by Django 4.2.3 on 2023-08-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_remove_participantenrollment_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantenrollment",
            name="state",
            field=models.CharField(
                choices=[
                    ("schvalen", "schválen"),
                    ("nahradnik", "nahradník"),
                    ("odmitnut", "odmítnut"),
                ],
                max_length=10,
                verbose_name="Stav přihlášky",
            ),
        ),
    ]
