# Generated by Django 4.2.2 on 2023-07-06 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_eventposition_template_alter_eventposition_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventposition",
            old_name="template",
            new_name="is_template",
        ),
    ]
