# Generated by Django 4.2.3 on 2023-08-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_participants_enroll_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participants_enroll_list",
            field=models.CharField(
                choices=[("nahradnik", "nahradník"), ("schvalen", "schválen")],
                default="nahradnik",
                max_length=10,
                verbose_name="Přidat nové účastníky jako",
            ),
        ),
    ]
