# Generated by Django 4.2.3 on 2023-07-08 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_rename_template_eventposition_is_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpositionassignment",
            name="count",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Počet",
            ),
        ),
    ]
