# Generated by Django 4.2.3 on 2023-07-10 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_eventpositionassignment_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventposition",
            name="is_template",
        ),
    ]
