# Generated by Django 4.2.3 on 2023-08-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_event_participants_enroll_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantenrollment",
            name="state",
            field=models.CharField(
                choices=[
                    ("schvalen", "schválen"),
                    ("nahradnik", "nahradník"),
                    ("odminut", "odmítnut"),
                ],
                max_length=10,
                verbose_name="Stav přihlášky",
            ),
        ),
    ]
