# Generated by Django 4.2.3 on 2023-07-11 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_remove_eventposition_is_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventposition",
            name="max_age",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Minimální věková hranice",
            ),
        ),
        migrations.AddField(
            model_name="eventposition",
            name="max_age_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Omezení maximálního věku"
            ),
        ),
        migrations.AddField(
            model_name="eventposition",
            name="min_age",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Minimální věková hranice",
            ),
        ),
        migrations.AddField(
            model_name="eventposition",
            name="min_age_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Omezení minimálního věku"
            ),
        ),
    ]
