# Generated by Django 4.2.3 on 2023-07-12 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_eventposition_max_age_eventposition_max_age_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventposition",
            name="required_features",
        ),
    ]
