# Generated by Django 4.2.3 on 2023-07-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
        ("events", "0009_remove_eventposition_required_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="positions",
            field=models.ManyToManyField(
                through="events.EventPositionAssignment", to="positions.eventposition"
            ),
        ),
        migrations.AlterField(
            model_name="eventpositionassignment",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="positions.eventposition",
            ),
        ),
        migrations.DeleteModel(
            name="EventPosition",
        ),
    ]
