# Generated by Django 4.2.2 on 2023-07-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0001_initial"),
        ("events", "0010_alter_event_positions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="requirements",
            field=models.ManyToManyField(
                through="events.EventRequirement", to="features.feature"
            ),
        ),
        migrations.AlterField(
            model_name="eventrequirement",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="features.feature"
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="bonuses",
            field=models.ManyToManyField(
                through="events.PriceListBonus", to="features.feature"
            ),
        ),
        migrations.AlterField(
            model_name="pricelistbonus",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="features.feature"
            ),
        ),
    ]
