# Generated by Django 4.2.3 on 2023-07-15 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_alter_event_requirements_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelist",
            name="bonuses",
        ),
        migrations.AlterUniqueTogether(
            name="pricelistbonus",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="pricelistbonus",
            name="feature",
        ),
        migrations.RemoveField(
            model_name="pricelistbonus",
            name="price_list",
        ),
    ]
