# Generated by Django 4.2.3 on 2023-07-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("price_lists", "0001_initial"),
        ("events", "0012_remove_pricelist_bonuses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="price_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="price_lists.pricelist",
            ),
        ),
        migrations.DeleteModel(
            name="PriceList",
        ),
        migrations.DeleteModel(
            name="PriceListBonus",
        ),
    ]
