# Generated by Django 4.2.3 on 2023-07-25 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_alter_event_price_list_delete_pricelist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="requirements",
        ),
    ]
