# Generated by Django 4.2.3 on 2023-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_remove_event_requirements"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="age_limit",
            new_name="min_age",
        ),
        migrations.AddField(
            model_name="event",
            name="min_age_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
