# Generated by Django 4.2.3 on 2023-08-01 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_rename_age_limit_event_min_age_event_min_age_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="min_age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Minimální věk účastníků",
            ),
        ),
    ]
