# Generated by Django 4.2.3 on 2023-08-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("events", "0016_alter_event_min_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="groups.group",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="participant_group_membership_required",
            field=models.BooleanField(default=False),
        ),
    ]
