# Generated by Django 4.2.3 on 2023-08-01 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_event_group_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="participant_group_membership_required",
            new_name="group_membership_required",
        ),
    ]
