# Generated by Django 4.2.3 on 2023-08-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0027_persontype"),
        ("positions", "0008_alter_eventposition_allowed_person_types"),
        ("events", "0019_persontype_event_allowed_person_types"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonType",
        ),
        migrations.AlterField(
            model_name="event",
            name="allowed_person_types",
            field=models.ManyToManyField(to="persons.persontype"),
        ),
    ]
