# Generated by Django 4.2.3 on 2023-08-11 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("events", "0021_enrollment_eventoccurrence_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventoccurrence",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="participantenrollment",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="enrollment",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="eventoccurrence",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
