# Generated by Django 4.2.3 on 2023-07-12 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("persons", "0023_feature_level_feature_lft_feature_rght_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Jméno")),
                ("min_age_enabled", models.BooleanField(default=False)),
                ("max_age_enabled", models.BooleanField(default=False)),
                (
                    "min_age",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "max_age",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                ("required_features", models.ManyToManyField(to="persons.feature")),
            ],
        ),
    ]
