# Generated by Django 4.2.2 on 2023-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0001_initial"),
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventposition",
            name="required_features",
            field=models.ManyToManyField(to="features.feature"),
        ),
    ]
