# Generated by Django 4.2.3 on 2023-11-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventposition",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Název"),
        ),
    ]
