# Generated by Django 4.2.3 on 2023-08-14 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventposition",
            name="max_age_enabled",
        ),
        migrations.RemoveField(
            model_name="eventposition",
            name="min_age_enabled",
        ),
        migrations.AlterField(
            model_name="eventposition",
            name="max_age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Maximální věk",
            ),
        ),
        migrations.AlterField(
            model_name="eventposition",
            name="min_age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Minimální věk",
            ),
        ),
    ]
