# Generated by Django 4.2.3 on 2023-08-16 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0002_eventposition_wage_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventposition",
            name="wage_hour",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Hodinová sazba",
            ),
            preserve_default=False,
        ),
    ]
