# Generated by Django 4.2.3 on 2023-08-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("positions", "0003_remove_eventposition_group_membership_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventposition",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="groups.group",
            ),
        ),
    ]
