# Generated by Django 4.2.3 on 2023-07-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("positions", "0003_eventposition_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("radny", "řádný člen"),
                            ("cekatel", "člen - čekatel"),
                            ("cestny", "čestný člen"),
                            ("dite", "dítě"),
                            ("externi", "externí spolupracovník"),
                            ("rodic", "rodič"),
                        ],
                        max_length=10,
                        verbose_name="Typ osoby",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="eventposition",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="groups.group",
            ),
        ),
        migrations.AddField(
            model_name="eventposition",
            name="allowed_person_types",
            field=models.ManyToManyField(to="positions.persontype"),
        ),
    ]
