# Generated by Django 4.2.3 on 2023-08-15 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0004_alter_eventposition_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventposition",
            name="bonus",
        ),
        migrations.AddField(
            model_name="eventposition",
            name="wage_hour",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Hodinová sazba",
            ),
        ),
    ]
