# Generated by Django 4.2.3 on 2023-07-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0004_persontype_alter_eventposition_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persontype",
            name="person_type",
            field=models.CharField(
                choices=[
                    ("radny", "řádný člen"),
                    ("cekatel", "člen - čekatel"),
                    ("cestny", "čestný člen"),
                    ("dite", "dítě"),
                    ("externi", "externí spolupracovník"),
                    ("rodic", "rodič"),
                ],
                max_length=10,
                unique=True,
                verbose_name="Typ osoby",
            ),
        ),
    ]
