# Generated by Django 4.2.3 on 2023-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0005_alter_persontype_person_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventposition",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Název"),
        ),
    ]
