# Generated by Django 4.2.3 on 2023-08-15 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0005_remove_eventposition_bonus_eventposition_wage_hour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventposition",
            name="wage_hour",
        ),
    ]
