# Generated by Django 4.2.3 on 2023-08-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0027_persontype"),
        ("positions", "0007_delete_persontype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventposition",
            name="allowed_person_types",
            field=models.ManyToManyField(to="persons.persontype"),
        ),
    ]
