from django.urls import path

from . import views

app_name = "one_time_events"

urlpatterns = [
    path("", views.OneTimeEventListView.as_view(), name="index"),
    path("vsechny/", views.OneTimeEventAdminListView.as_view(), name="list-admin"),
    path(
        "<int:pk>/",
        views.OneTimeEventDetailView.as_view(),
        name="detail",
    ),
    path(
        "pridat/", views.OneTimeEventCreateView.as_view(), name="add"
    ),  # TODO: permissions
    path(
        "<int:pk>/upravit/",
        views.OneTimeEventUpdateView.as_view(),
        name="edit",
    ),
    path(
        "<int:pk>/upravit-dochazku-treninku",
        views.EditTrainingCategoryView.as_view(),
        name="edit-training-category",
    ),
    path(
        "<int:event_id>/pridat-prihlasku/",
        views.OneTimeEventParticipantEnrollmentCreateView.as_view(),
        name="create-participant-enrollment",
    ),
    path(
        "<int:event_id>/upravit-prihlasku/<int:pk>",
        views.OneTimeEventParticipantEnrollmentUpdateView.as_view(),
        name="edit-participant-enrollment",
    ),
    path(
        "<int:event_id>/smazat-prihlasku/<int:pk>",
        views.OneTimeEventParticipantEnrollmentDeleteView.as_view(),
        name="delete-participant-enrollment",
    ),
    path(
        "<int:event_id>/prihlasit-ucastnika/",
        views.OneTimeEventEnrollMyselfParticipantView.as_view(),
        name="enroll-myself-participant",
    ),
    path(
        "<int:occurrence_id>/pridat-organizatora-na-den",
        views.AddOrganizerForOccurrenceView.as_view(),
        name="add-organizer-for-occurrence",
    ),
    path(
        "<int:occurrence_id>/upravit-organizatora-na-den/<int:pk>",
        views.EditOrganizerForOccurrenceView.as_view(),
        name="edit-organizer-for-occurrence",
    ),
    path(
        "<int:occurrence_id>/smazat-organizatora-na-den/<int:pk>",
        views.DeleteOrganizerForOccurrenceView.as_view(),
        name="delete-organizer-from-occurrence",
    ),
    path(
        "<int:event_id>/hromadne-odebrani-organizatora/",
        views.BulkDeleteOrganizerFromOneTimeEventView.as_view(),
        name="bulk-delete-organizer",
    ),
    path(
        "<int:event_id>/hromadne-pridani-organizatora/",
        views.BulkAddOrganizerToOneTimeEventView.as_view(),
        name="bulk-add-organizer",
    ),
    path(
        "<int:pk>/hromadne-schvalit",
        views.OneTimeEventBulkApproveParticipantsView.as_view(),
        name="bulk-approve-participants",
    ),
    path(
        "<int:occurrence_id>/prihlasit-organizatora-na-den/<int:position_assignment_id>",
        views.OneTimeEventEnrollMyselfOrganizerOccurrenceView.as_view(),
        name="enroll-myself-organizer-occurrence",
    ),
    path(
        "<int:occurrence_id>/odhlasit-organizatora-na-den/<int:pk>",
        views.OneTimeEventUnenrollMyselfOrganizerOccurrenceView.as_view(),
        name="unenroll-myself-organizer-occurrence",
    ),
    path(
        "<int:event_id>/odhlasit-organizatora/",
        views.OneTimeEventUnenrollMyselfOrganizerView.as_view(),
        name="unenroll-myself-organizer",
    ),
    path(
        "<int:event_id>/prihlasit-organizatora/",
        views.OneTimeEventEnrollMyselfOrganizerView.as_view(),
        name="enroll-myself-organizer",
    ),
    path(
        "<int:event_id>/detail-dne/<int:pk>/",
        views.OneTimeOccurrenceDetailView.as_view(),
        name="occurrence-detail",
    ),
    path(
        "<int:event_id>/detail-dne/<int:pk>/vyplnit-dochazku/",
        views.OneTimeEventFillAttendanceView.as_view(),
        name="fill-attendance",
    ),
    path(
        "<int:event_id>/detail-dne/<int:pk>/schvalit-den/",
        views.ApproveOccurrenceView.as_view(),
        name="approve-occurrence",
    ),
    path(
        "<int:event_id>/detail-dne/<int:pk>/znovu-otevrit/",
        views.ReopenOneTimeEventOccurrenceView.as_view(),
        name="reopen-occurrence",
    ),
    path(
        "<int:event_id>/detail-dne/<int:pk>/zrusit-schvaleni/",
        views.CancelOccurrenceApprovementView.as_view(),
        name="cancel-occurrence-approvement",
    ),
    path(
        "<int:event_id>/zobrazit-dny-k-uzavreni/",
        views.OneTimeEventOpenOccurrencesOverviewView.as_view(),
        name="open-occurrences-overview",
    ),
    path(
        "<int:event_id>/zobrazit-dny-ke-schvaleni/",
        views.OneTimeEventClosedOccurrencesOverviewView.as_view(),
        name="closed-occurrences-overview",
    ),
    path(
        "<int:event_id>/zobrazit-dochazku/",
        views.OneTimeEventShowAttendanceView.as_view(),
        name="show-attendance",
    ),
    path(
        "<int:event_id>/exportovat-ucastniky/",
        views.OneTimeEventExportParticipantsView.as_view(),
        name="export-participants",
    ),
    path(
        "<int:event_id>/exportovat-organizatory/",
        views.OneTimeEventExportOrganizersView.as_view(),
        name="export-organizers",
    ),
    path(
        "<int:event_id>/detail-dne/<int:pk>/exportovat-pritomne-organizatory/",
        views.OneTimeEventExportOrganizersOccurrenceView.as_view(),
        name="export-organizers-occurrence",
    ),
    path(
        "<int:pk>/duplikovat/",
        views.OneTimeEventCreateDuplicateView.as_view(),
        name="create-duplicate",
    ),
    path(
        "<int:pk>/upravit-duplikat/",
        views.OneTimeEventUpdateDuplicateView.as_view(),
        name="edit-duplicate",
    ),
]
