# Generated by Django 4.2.3 on 2023-09-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("one_time_events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="onetimeeventoccurrence",
            old_name="attending_participants",
            new_name="participants",
        ),
        migrations.AddField(
            model_name="onetimeeventparticipantattendance",
            name="state",
            field=models.CharField(
                choices=[("prezence", "prezence"), ("absence", "absence")],
                default=1,
                max_length=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizeroccurrenceassignment",
            name="state",
            field=models.CharField(
                choices=[("prezence", "prezence"), ("absence", "absence")],
                default=1,
                max_length=8,
            ),
            preserve_default=False,
        ),
    ]
