# Generated by Django 4.2.3 on 2023-08-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("one_time_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimeeventoccurrence",
            name="date",
            field=models.DateField(verbose_name="Den konání"),
        ),
    ]
