# Generated by Django 4.2.3 on 2023-08-17 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("one_time_events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="onetimeevent",
            old_name="participants_of_specific_training_requirement",
            new_name="training_category",
        ),
    ]
