# Generated by Django 4.2.3 on 2023-08-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
        ("one_time_events", "0002_alter_onetimeeventoccurrence_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimeevent",
            name="enrolled_participants",
            field=models.ManyToManyField(
                related_name="one_time_event_participant_enrollment_set",
                through="one_time_events.OneTimeEventParticipantEnrollment",
                to="persons.person",
            ),
        ),
    ]
