# Generated by Django 4.2.3 on 2023-08-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
        (
            "one_time_events",
            "0002_rename_participants_of_specific_training_requirement_onetimeevent_participants_of_training_category_",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimeeventparticipantenrollment",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.person",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="onetimeeventoccurrence",
            name="organizers_assignment",
            field=models.ManyToManyField(
                related_name="one_time_event_occurrence_organizer_position_assignment_set",
                to="one_time_events.onetimeeventoccurrenceorganizerpositionassignment",
            ),
        ),
    ]
