# Generated by Django 4.2.3 on 2023-08-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
        ("one_time_events", "0002_onetimeeventparticipantenrollment_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimeeventparticipantenrollment",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.transaction",
            ),
        ),
    ]
