# Generated by Django 4.2.2 on 2023-10-02 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "one_time_events",
            "0002_rename_attending_participants_onetimeeventoccurrence_participants_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onetimeevent",
            options={
                "permissions": [
                    ("komercni", "Správce komerčních akcí"),
                    ("kurz", "Správce kurzů"),
                    ("prezentacni", "Správce prezentačních akcí"),
                ]
            },
        ),
    ]
