# Generated by Django 4.2.3 on 2023-08-24 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_personhourlyrate_hourly_rate"),
        ("one_time_events", "0003_onetimeeventparticipantenrollment_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onetimeeventparticipantenrollment",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="onetimeeventparticipantenrollment",
            unique_together={("one_time_event", "person")},
        ),
    ]
