# Generated by Django 4.2.3 on 2023-11-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("one_time_events", "0003_alter_onetimeevent_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimeevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("komercni", "komerční"),
                    ("kurz", "kurz"),
                    ("prezentacni", "prezentační"),
                    ("pro-deti", "pro děti"),
                ],
                max_length=11,
                verbose_name="Druh události",
            ),
        ),
    ]
