# Generated by Django 4.2.3 on 2023-08-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("one_time_events", "0004_alter_onetimeevent_default_participation_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimeevent",
            name="default_participation_fee",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Standardní výše poplatku pro účastníky",
            ),
        ),
    ]
