# Generated by Django 4.2.7 on 2023-12-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("one_time_events", "0004_alter_onetimeevent_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onetimeevent",
            options={
                "permissions": [
                    ("komercni", "Správce komerčních událostí"),
                    ("kurz", "Správce kurzů"),
                    ("prezentacni", "Správce prezentačních událostí"),
                    ("pro-deti", "Správce událostí pro děti"),
                    ("spolecenska", "Správce společenských událostí"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="onetimeevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("komercni", "komerční"),
                    ("kurz", "kurz"),
                    ("prezentacni", "prezentační"),
                    ("pro-deti", "pro děti"),
                    ("spolecenska", "společenská"),
                ],
                max_length=11,
                verbose_name="Druh události",
            ),
        ),
    ]
