# Generated by Django 5.0 on 2023-12-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_time_events', '0005_alter_onetimeevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimeevent',
            options={'base_manager_name': 'objects'},
        ),
    ]
