# Generated by Django 4.2.5 on 2023-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='name',
            field=models.CharField(default='_', max_length=50, verbose_name='Název'),
            preserve_default=False,
        ),
    ]
