# Generated by Django 4.2.2 on 2023-07-09 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"permissions": [("stranky", "Správce textových stránek")]},
        ),
    ]
