# Generated by Django 4.2.2 on 2023-07-10 11:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_page_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name="Obsah"),
        ),
    ]
