# Generated by Django 4.2.3 on 2023-08-15 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import vzs.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("features", "0001_initial"),
        ("persons", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FioSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_fio_fetch_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1899, 12, 31, 23, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FioTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_settled", models.DateField(null=True)),
                ("fio_id", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Suma")),
                (
                    "reason",
                    models.CharField(max_length=150, verbose_name="Popis transakce"),
                ),
                ("date_due", models.DateField(verbose_name="Datum splatnosti")),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                        verbose_name="Událost",
                    ),
                ),
                (
                    "feature_assigment",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="features.featureassignment",
                        verbose_name="Vybavení",
                    ),
                ),
                (
                    "fio_transaction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.fiotransaction",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="persons.person",
                        verbose_name="Osoba",
                    ),
                ),
            ],
            options={
                "permissions": [("spravce_transakci", "Správce transakcí")],
            },
            bases=(vzs.models.ExportableCSVMixin, models.Model),
        ),
    ]
