# Generated by Django 4.2.2 on 2023-07-12 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0009_alter_eventposition_max_age_and_more"),
        ("persons", "0024_delete_fiosettings_remove_transaction_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FioSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_fio_fetch_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1899, 12, 31, 23, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FioTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_settled", models.DateField(null=True)),
                ("fio_id", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Suma")),
                (
                    "reason",
                    models.CharField(max_length=150, verbose_name="Popis transakce"),
                ),
                ("date_due", models.DateField(verbose_name="Datum splatnosti")),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                    ),
                ),
                (
                    "feature_assigment",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="persons.featureassignment",
                    ),
                ),
                (
                    "fio_transaction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.fiotransaction",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "permissions": [("spravce_transakci", "Správce transakcí")],
            },
        ),
    ]
