# Generated by Django 4.2.2 on 2023-08-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=150, verbose_name="Popis transakce"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="bulk_transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.bulktransaction",
            ),
        ),
    ]
