# Generated by Django 4.2.2 on 2023-07-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_alter_event_price_list_delete_pricelist_and_more"),
        ("features", "0002_feature_tier_alter_featureassignment_person"),
        ("persons", "0026_remove_staticgroup_group_ptr_and_more"),
        ("transactions", "0002_alter_transaction_feature_assigment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Událost",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="feature_assigment",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="features.featureassignment",
                verbose_name="Vybavení",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="persons.person",
                verbose_name="Osoba",
            ),
        ),
    ]
