# Generated by Django 5.0 on 2023-12-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_bulktransaction_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
    ]
