# Generated by Django 4.2.2 on 2024-01-13 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulktransaction",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-pk"]},
        ),
    ]
