# Generated by Django 4.2.3 on 2023-08-27 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
        ("persons", "0001_initial"),
        ("trainings", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrainingCoachPositionAssignment",
            new_name="CoachPositionAssignment",
        ),
    ]
