# Generated by Django 4.2.3 on 2023-08-28 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_remove_organizerassignment_position_assignment"),
        ("trainings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachoccurrenceassignment",
            name="position_assignment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.eventpositionassignment",
                verbose_name="Pozice události",
            ),
            preserve_default=False,
        ),
    ]
