# Generated by Django 4.2.2 on 2023-08-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trainings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingreplaceabilityforparticipants",
            name="symmetric",
        ),
        migrations.AlterField(
            model_name="trainingreplaceabilityforparticipants",
            name="training_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replaceable_training_1",
                to="trainings.training",
            ),
        ),
        migrations.AlterField(
            model_name="trainingreplaceabilityforparticipants",
            name="training_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replaceable_training_2",
                to="trainings.training",
            ),
        ),
    ]
