# Generated by Django 4.2.3 on 2023-08-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_personhourlyrate_hourly_rate"),
        ("trainings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingparticipantenrollment",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.person",
            ),
            preserve_default=False,
        ),
    ]
