# Generated by Django 4.2.3 on 2023-08-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
        ("positions", "0001_initial"),
        ("trainings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingCoachPositionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="persons.person"
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.eventposition",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainings.training",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="training",
            name="coaches",
            field=models.ManyToManyField(
                related_name="training_coach_position_assignment_set",
                through="trainings.TrainingCoachPositionAssignment",
                to="persons.person",
            ),
        ),
    ]
