# Generated by Django 4.2.3 on 2023-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
        ("trainings", "0002_alter_training_ct_from_alter_training_ct_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="coaches_assignment",
            field=models.ManyToManyField(
                related_name="training_coach_position_assignment_set",
                to="trainings.trainingcoachpositionassignment",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="enrolled_participants",
            field=models.ManyToManyField(
                related_name="training_participant_enrollment_set",
                through="trainings.TrainingParticipantEnrollment",
                to="persons.person",
            ),
        ),
        migrations.AlterField(
            model_name="trainingoccurrence",
            name="missing_coaches_excused",
            field=models.ManyToManyField(
                related_name="training_one_time_coach_position_set",
                through="trainings.TrainingOneTimeCoachPosition",
                to="persons.person",
            ),
        ),
        migrations.AlterField(
            model_name="trainingoccurrence",
            name="missing_participants_excused",
            field=models.ManyToManyField(
                related_name="training_occurrence_attendance_compensation_opportunity_set",
                through="trainings.TrainingOccurrenceAttendanceCompensationOpportunity",
                to="persons.person",
            ),
        ),
    ]
