# Generated by Django 4.2.3 on 2023-08-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
        ("trainings", "0002_trainingparticipantenrollment_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingparticipantenrollment",
            name="transactions",
            field=models.ManyToManyField(null=True, to="transactions.transaction"),
        ),
    ]
