# Generated by Django 4.2.3 on 2023-09-15 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_personhourlyrate_hourly_rate"),
        (
            "trainings",
            "0002_rename_attending_participants_trainingoccurrence_participants_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingparticipantattendance",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.person",
                verbose_name="Osoba",
            ),
        ),
    ]
