# Generated by Django 4.2.3 on 2023-08-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
        (
            "trainings",
            "0002_remove_trainingreplaceabilityforparticipants_symmetric_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingparticipantenrollment",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.person",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingparticipantenrollment",
            name="weekdays",
            field=models.ManyToManyField(
                related_name="training_weekdays_set", to="trainings.trainingweekdays"
            ),
        ),
    ]
