# Generated by Django 4.2.3 on 2023-08-19 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_personhourlyrate_hourly_rate"),
        ("trainings", "0002_trainingparticipantenrollment_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingparticipantenrollment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.person",
                verbose_name="Osoba",
            ),
        ),
    ]
