# Generated by Django 4.2.3 on 2023-08-27 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
        ("persons", "0001_initial"),
        (
            "trainings",
            "0002_rename_trainingcoachpositionassignment_coachpositionassignment",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coachpositionassignment",
            unique_together={("person", "training", "position")},
        ),
    ]
