# Generated by Django 4.2.3 on 2023-08-24 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainings", "0003_trainingparticipantenrollment_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingweekdays",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
