# Generated by Django 4.2.3 on 2023-08-13 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
        ("trainings", "0003_alter_training_coaches_assignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingWeekdays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="training",
            name="enrolled_participants",
            field=models.ManyToManyField(
                related_name="training_participant_enrollment_1_set",
                through="trainings.TrainingParticipantEnrollment",
                to="persons.person",
            ),
        ),
        migrations.AddField(
            model_name="trainingparticipantenrollment",
            name="weekdays",
            field=models.ManyToManyField(to="trainings.trainingweekdays"),
        ),
    ]
