# Generated by Django 4.2.3 on 2023-08-25 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_personhourlyrate_hourly_rate"),
        ("trainings", "0003_trainingparticipantenrollment_transactions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingparticipantenrollment",
            options={},
        ),
        migrations.AlterField(
            model_name="trainingweekdays",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingparticipantenrollment",
            unique_together={("training", "person")},
        ),
    ]
