# Generated by Django 4.2.3 on 2023-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_personhourlyrate_hourly_rate"),
        ("trainings", "0003_alter_trainingparticipantenrollment_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="enrolled_participants",
            field=models.ManyToManyField(
                related_name="training_participant_enrollment_set",
                through="trainings.TrainingParticipantEnrollment",
                to="persons.person",
            ),
        ),
    ]
