# Generated by Django 4.2.3 on 2023-08-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
        ("trainings", "0003_trainingparticipantenrollment_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingparticipantenrollment",
            name="transactions",
            field=models.ManyToManyField(to="transactions.transaction"),
        ),
    ]
