# Generated by Django 4.2.3 on 2023-08-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
        ("events", "0003_remove_organizeroccurrenceassignment_position_and_more"),
        ("trainings", "0003_alter_coachpositionassignment_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coachpositionassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="coachpositionassignment",
            name="position_assignment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.eventpositionassignment",
                verbose_name="Pozice události",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coachpositionassignment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.person",
                verbose_name="Osoba",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coachpositionassignment",
            unique_together={("person", "training")},
        ),
        migrations.RemoveField(
            model_name="coachpositionassignment",
            name="position",
        ),
    ]
