# Generated by Django 4.2.3 on 2023-08-13 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trainings", "0004_trainingweekdays_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingoccurrence",
            options={"ordering": ["datetime_start"]},
        ),
    ]
