# Generated by Django 4.2.3 on 2023-08-13 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trainings", "0005_alter_trainingoccurrence_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingoccurrence",
            options={"base_manager_name": "objects"},
        ),
    ]
