# Generated by Django 4.2.3 on 2023-07-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("features", "0002_alter_featureassignment_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Název")),
                ("salary_base", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PriceListBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bonus", models.PositiveIntegerField()),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="features.feature",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="price_lists.pricelist",
                    ),
                ),
            ],
            options={
                "unique_together": {("price_list", "feature")},
            },
        ),
        migrations.AddField(
            model_name="pricelist",
            name="bonuses",
            field=models.ManyToManyField(
                through="price_lists.PriceListBonus", to="features.feature"
            ),
        ),
    ]
