# Generated by Django 4.2.3 on 2023-07-17 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("price_lists", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricelist",
            old_name="bonuses",
            new_name="bonus_features",
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="salary_base",
            field=models.PositiveIntegerField(verbose_name="Základní výplata"),
        ),
        migrations.AlterField(
            model_name="pricelistbonus",
            name="bonus",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Bonusová částka",
            ),
        ),
    ]
