# Generated by Django 4.2.3 on 2023-07-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("price_lists", "0003_rename_bonus_pricelistbonus_extra_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
    ]
