# Generated by Django 4.2.3 on 2023-07-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("price_lists", "0004_pricelist_is_template"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricelistbonus",
            old_name="extra_payment",
            new_name="extra_fee",
        ),
        migrations.AddField(
            model_name="pricelist",
            name="participant_fee",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Poplatek za účast"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="salary_base",
            field=models.PositiveIntegerField(
                verbose_name="Základní výplata organizátorů"
            ),
        ),
    ]
