# Generated by Django 4.2.3 on 2023-07-22 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("price_lists", "0005_rename_extra_payment_pricelistbonus_extra_fee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricelistbonus",
            old_name="extra_fee",
            new_name="extra_salary",
        ),
    ]
