# Generated by Django 4.2.2 on 2023-08-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonHourlyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=20, verbose_name="Kategorie akcí"),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Hodinová sazba"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_rates",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "unique_together": {("person", "event_type")},
            },
        ),
    ]
