# Generated by Django 4.2.1 on 2023-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
