# Generated by Django 4.2.3 on 2023-08-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0002_personhourlyrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personhourlyrate",
            name="hourly_rate",
            field=models.PositiveIntegerField(verbose_name="Hodinová sazba"),
        ),
    ]
