# Generated by Django 4.2.2 on 2023-06-13 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_featureassignment_date_expire"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\d{2}(0[1-9]|1[0-2]|5[1-9]|6[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])\\/?\\d{3,4}",
                        "Rodné číslo má špatný tvar.",
                    )
                ],
                verbose_name="Rodné číslo",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Město"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="health_insurance_company",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    ("111", "111 - Všeobecná zdravotní pojišťovna České republiky"),
                    ("201", "201 - Vojenská zdravotní pojišťovna České republiky"),
                    ("205", "205 - Česká průmyslová zdravotní pojišťovna"),
                    (
                        "207",
                        "207 - Oborová zdravotní pojišťovna zaměstnanců bank, pojišťoven a stavebnictví",
                    ),
                    ("209", "209 - Zaměstnanecká pojišťovna Škoda"),
                    (
                        "211",
                        "211 - Zdravotní pojišťovna ministerstva vnitra České republiky",
                    ),
                    ("213", "213 - Revírní bratrská pokladna, zdravotní pojišťovna"),
                ],
                null=True,
                verbose_name="Zdravotní pojišťovna",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="postcode",
            field=models.IntegerField(blank=True, null=True, verbose_name="PSČ"),
        ),
        migrations.AddField(
            model_name="person",
            name="sex",
            field=models.CharField(
                choices=[("M", "muž"), ("F", "žena")],
                default="M",
                max_length=1,
                verbose_name="Pohlaví",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="street",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Ulice a číslo popisné",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="swimming_time",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\d{2}:\\d{2}\\.\\d{2}",
                        "Čas na 100m musí být v formátu mm:ss.ss.",
                    )
                ],
                verbose_name="Čas na 100m",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Datum narození"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="E-mailová adressa"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Křestní jméno"),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Příjmení"),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_type",
            field=models.CharField(
                choices=[
                    ("dite", "člen dítě"),
                    ("dospely", "člen dospělý"),
                    ("cekatel", "člen čekatel"),
                    ("cestny", "čestný člen"),
                    ("externi", "externí spolupracovník"),
                    ("rodic", "rodič"),
                ],
                max_length=10,
                verbose_name="Typ osoby",
            ),
        ),
    ]
