# Generated by Django 4.2.2 on 2023-06-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_featureassignment_date_expire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="category",
        ),
        migrations.AddField(
            model_name="feature",
            name="parent",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.feature",
            ),
        ),
    ]
