# Generated by Django 4.2.2 on 2023-11-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_personhourlyrate_hourly_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="E-mailová adressa",
            ),
        ),
    ]
