# Generated by Django 5.0 on 2023-12-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_alter_person_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
