# Generated by Django 4.2.2 on 2023-06-12 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0004_remove_feature_category_feature_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.feature",
            ),
        ),
    ]
