# Generated by Django 4.2.2 on 2023-06-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0005_alter_feature_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="assignable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="issuer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="licence_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
