# Generated by Django 4.2.2 on 2024-01-13 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0007_alter_person_birth_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="personhourlyrate",
            options={
                "ordering": ["person__last_name", "person__first_name", "event_type"]
            },
        ),
    ]
