# Generated by Django 4.2.2 on 2023-06-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0007_rename_licence_id_feature_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="persons.feature",
            ),
        ),
    ]
