# Generated by Django 4.2.2 on 2023-06-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0008_alter_feature_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="code",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="issuer",
        ),
        migrations.AddField(
            model_name="feature",
            name="collect_codes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feature",
            name="collect_issuers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="featureassignment",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="featureassignment",
            name="issuer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
