# Generated by Django 4.2.2 on 2023-06-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0009_remove_feature_code_remove_feature_issuer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="assignable",
            field=models.BooleanField(default=True, verbose_name="Přiřaditelné osobě"),
        ),
        migrations.AlterField(
            model_name="feature",
            name="collect_issuers",
            field=models.BooleanField(
                default=False, verbose_name="Evidovat vydavatele kvalifikace"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Název"),
        ),
        migrations.AlterField(
            model_name="feature",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="persons.feature",
                verbose_name="Nadřazená kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="tier",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Poplatek"),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_type",
            field=models.CharField(
                choices=[
                    ("radny", "řádný člen"),
                    ("cekatel", "člen - čekatel"),
                    ("cestny", "čestný člen"),
                    ("dite", "dítě"),
                    ("externi", "externí spolupracovník"),
                    ("rodic", "rodič"),
                ],
                max_length=10,
            ),
        ),
    ]
