# Generated by Django 4.2.2 on 2023-06-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0012_person_birth_number_person_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="health_insurance_company",
            field=models.CharField(
                blank=True,
                choices=[
                    ("111", "111 - Všeobecná zdravotní pojišťovna České republiky"),
                    ("201", "201 - Vojenská zdravotní pojišťovna České republiky"),
                    ("205", "205 - Česká průmyslová zdravotní pojišťovna"),
                    (
                        "207",
                        "207 - Oborová zdravotní pojišťovna zaměstnanců bank, pojišťoven a stavebnictví",
                    ),
                    ("209", "209 - Zaměstnanecká pojišťovna Škoda"),
                    (
                        "211",
                        "211 - Zdravotní pojišťovna ministerstva vnitra České republiky",
                    ),
                    ("213", "213 - Revírní bratrská pokladna, zdravotní pojišťovna"),
                ],
                max_length=3,
                null=True,
                verbose_name="Zdravotní pojišťovna",
            ),
        ),
        migrations.AlterField(
            model_name="staticgroup",
            name="members",
            field=models.ManyToManyField(related_name="groups", to="persons.person"),
        ),
    ]
