# Generated by Django 4.2.2 on 2023-06-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0013_alter_person_health_insurance_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Název skupiny"),
        ),
    ]
