# Generated by Django 4.2.2 on 2023-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0014_alter_group_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="managed_people",
        ),
        migrations.AddField(
            model_name="person",
            name="managed_persons",
            field=models.ManyToManyField(
                related_name="managed_by", to="persons.person"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="feature_type",
            field=models.CharField(
                choices=[("K", "kvalifikace"), ("V", "vybavení"), ("O", "oprávnění")],
                max_length=1,
            ),
        ),
    ]
