# Generated by Django 4.2.2 on 2023-06-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0014_alter_group_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"default_permissions": [], "permissions": [("ucetni", "Účetní")]},
        ),
        migrations.AlterField(
            model_name="feature",
            name="feature_type",
            field=models.CharField(
                choices=[("K", "kvalifikace"), ("V", "vybavení"), ("O", "oprávnění")],
                max_length=1,
            ),
        ),
    ]
