# Generated by Django 4.2.2 on 2023-06-23 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "persons",
            "0015_remove_person_managed_people_person_managed_persons_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"default_permissions": [], "permissions": [("ucetni", "Účetní")]},
        ),
    ]
