# Generated by Django 4.2.2 on 2023-06-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "persons",
            "0015_group_google_as_members_authority_group_google_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="google_email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="E-mailová adresa skupiny v Google Workspace",
            ),
        ),
    ]
