# Generated by Django 4.2.2 on 2023-07-07 10:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0016_alter_transaction_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FioSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_fio_fetch_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1899, 12, 31, 23, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FioTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_settled", models.DateField(null=True)),
                ("fio_id", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="date",
        ),
        migrations.AddField(
            model_name="transaction",
            name="date_due",
            field=models.DateField(default=None, verbose_name="Datum splatnosti"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(verbose_name="Suma"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="persons.person",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reason",
            field=models.CharField(max_length=150, verbose_name="Popis transakce"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="fio_transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="persons.fiotransaction",
            ),
        ),
    ]
