# Generated by Django 4.2.2 on 2023-07-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0016_alter_transaction_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="date",
        ),
        migrations.AddField(
            model_name="transaction",
            name="date_due",
            field=models.DateField(default=None, verbose_name="Datum splatnosti"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="date_settled",
            field=models.DateField(null=True, verbose_name="Datum realizace"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(verbose_name="Suma"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="persons.person",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reason",
            field=models.CharField(max_length=150, verbose_name="Popis transakce"),
        ),
    ]
