# Generated by Django 4.2.2 on 2023-07-06 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0017_remove_transaction_date_transaction_date_due_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FioSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_fio_fetch_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1899, 12, 31, 23, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
