# Generated by Django 4.2.2 on 2023-07-08 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0017_fiosettings_fiotransaction_remove_transaction_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={
                "permissions": [
                    ("spravce_kvalifikaci", "Správce kvalifikací"),
                    ("spravce_opravneni", "Správce oprávnění"),
                    ("spravce_vybaveni", "Správce vybavení"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"permissions": [("spravce_skupin", "Správce skupin")]},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "permissions": [
                    ("clenska_zakladna", "Správce členské základny"),
                    ("detska_clenska_zakladna", "Správce dětské členské základny"),
                    (
                        "bazenova_clenska_zakladna",
                        "Správce bazénové dětské členské základny",
                    ),
                    (
                        "lezecka_clenska_zakladna",
                        "Správce lezecké dětské členské základny",
                    ),
                    ("dospela_clenska_zakladna", "Správce dospělé členské základny"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"permissions": [("spravce_transakci", "Správce transakcí")]},
        ),
    ]
