# Generated by Django 4.2.2 on 2023-07-11 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0021_transaction_feature_assigment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="tier",
            new_name="fee",
        ),
    ]
