# Generated by Django 4.2.2 on 2023-07-12 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0023_feature_level_feature_lft_feature_rght_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FioSettings",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="event",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="feature_assigment",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="fio_transaction",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="person",
        ),
        migrations.DeleteModel(
            name="FioTransaction",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
