# Generated by Django 4.2.2 on 2023-07-13 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0025_alter_featureassignment_unique_together_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #    model_name='staticgroup',
        #    name='group_ptr',
        # ),
        migrations.RemoveField(
            model_name="staticgroup",
            name="members",
        ),
        migrations.DeleteModel(
            name="DynamicGroup",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="StaticGroup",
        ),
    ]
