# Generated by Django 4.2.2 on 2023-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0027_persontype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="person_type",
            field=models.CharField(
                choices=[
                    ("radny", "řádný člen"),
                    ("cekatel", "člen - čekatel"),
                    ("cestny", "čestný člen"),
                    ("dite", "dítě"),
                    ("externi", "externí spolupracovník"),
                    ("rodic", "rodič"),
                    ("byvaly", "bývalý člen"),
                ],
                max_length=10,
                verbose_name="Typ osoby",
            ),
        ),
    ]
