# Generated by Django 4.2.3 on 2023-08-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0028_alter_person_person_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persontype",
            name="person_type",
            field=models.CharField(
                choices=[
                    ("radny", "řádný člen"),
                    ("cekatel", "člen - čekatel"),
                    ("cestny", "čestný člen"),
                    ("dite", "dítě"),
                    ("externi", "externí spolupracovník"),
                    ("rodic", "rodič"),
                    ("byvaly", "bývalý člen"),
                ],
                max_length=10,
                unique=True,
                verbose_name="Typ osoby",
            ),
        ),
    ]
