# Generated by Django 4.2.2 on 2023-07-13 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("persons", "0026_remove_staticgroup_group_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Název skupiny"),
                ),
                (
                    "google_email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="E-mailová adresa skupiny v Google Workspace",
                    ),
                ),
                (
                    "google_as_members_authority",
                    models.BooleanField(
                        verbose_name="Je Google autorita seznamu členů?"
                    ),
                ),
            ],
            options={
                "permissions": [("spravce_skupin", "Správce skupin")],
            },
        ),
        migrations.CreateModel(
            name="DynamicGroup",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="groups.group",
                    ),
                ),
            ],
            bases=("groups.group",),
        ),
        migrations.CreateModel(
            name="StaticGroup",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="groups.group",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(related_name="groups", to="persons.person"),
                ),
            ],
            bases=("groups.group",),
        ),
    ]
