# Generated by Django 4.2.2 on 2023-08-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0026_remove_staticgroup_group_ptr_and_more"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staticgroup",
            name="members",
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(related_name="groups", to="persons.person"),
        ),
        migrations.DeleteModel(
            name="DynamicGroup",
        ),
        migrations.DeleteModel(
            name="StaticGroup",
        ),
    ]
