# Generated by Django 4.2.2 on 2023-07-13 07:21

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("persons", "0024_delete_fiosettings_remove_transaction_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("K", "kvalifikace"),
                            ("V", "vybavení"),
                            ("O", "oprávnění"),
                        ],
                        max_length=1,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Název")),
                (
                    "assignable",
                    models.BooleanField(
                        default=True, verbose_name="Přiřaditelné osobě"
                    ),
                ),
                ("never_expires", models.BooleanField(blank=True, null=True)),
                (
                    "fee",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Poplatek"
                    ),
                ),
                (
                    "collect_issuers",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Evidovat vydavatele kvalifikace",
                    ),
                ),
                ("collect_codes", models.BooleanField(blank=True, null=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="features.feature",
                        verbose_name="Nadřazená kategorie",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("spravce_kvalifikaci", "Správce kvalifikací"),
                    ("spravce_opravneni", "Správce oprávnění"),
                    ("spravce_vybaveni", "Správce vybavení"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeatureAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_assigned", models.DateField()),
                ("date_expire", models.DateField(blank=True, null=True)),
                ("issuer", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="features.feature",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="persons.person"
                    ),
                ),
            ],
            options={
                "unique_together": {("person", "feature")},
            },
        ),
    ]
