# Generated by Django 4.2.2 on 2023-07-16 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0026_remove_staticgroup_group_ptr_and_more"),
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="tier",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Úroveň"
            ),
        ),
        migrations.AlterField(
            model_name="featureassignment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.person",
                verbose_name="Osoba",
            ),
        ),
    ]
