# Generated by Django 4.2.3 on 2023-07-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0026_remove_staticgroup_group_ptr_and_more"),
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureassignment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.person",
                verbose_name="Osoba",
            ),
        ),
    ]
