# Generated by Django 4.2.3 on 2023-08-16 09:45

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("persons", "0001_initial"),
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureassignment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.person",
                verbose_name="Osoba",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="features.feature",
                verbose_name="Nadřazená kategorie",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featureassignment",
            unique_together={("person", "feature")},
        ),
    ]
