# Generated by Django 4.2.2 on 2023-08-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureassignment",
            name="date_returned",
            field=models.DateField(blank=True, null=True),
        ),
    ]
