# Generated by Django 5.0 on 2023-12-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_featureassignment_expiry_email_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={},
        ),
    ]
