# Generated by Django 5.0 on 2023-12-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_alter_feature_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('kvalifikace', 'kvalifikace'), ('vybaveni', 'vybavení'), ('opravneni', 'oprávnění')], max_length=15),
        ),
    ]
