# Generated by Django 4.2.2 on 2024-01-13 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0006_alter_feature_feature_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featureassignment",
            options={"ordering": ["-date_assigned"]},
        ),
    ]
